ignored:
  - DL3008  # Pin versions in apt-get install. Ignored to allow more flexible package versions.
  - DL3018  # Pin versions in apk add. Not applicable on Debian-based images, often ignored.
  - DL3015  # Avoid additional packages by combining apt-get install. Ignored for readability/modularity.
  - DL4006  # Set SHELL explicitly. Often ignored if base image handles it or when using Bash by default.
  - DL3013  # Avoid installing packages not needed in final image. Ignored in multi-stage builds for clarity.