name: "Sanitize string"
description: "Sanitize a string by escaping commas and optionally other characters"

inputs:
  value:
    description: "The string to sanitize"
    required: true

outputs:
  sanitized:
    description: "The sanitized string"
    value: ${{ steps.sanitize_step.outputs.sanitized }}

runs:
  using: "composite"
  steps:
    - name: Sanitize string
      id: sanitize_step
      shell: bash
      run: |
        CLEANED=$(echo "${{ inputs.value }}" | tr -d ',' | tr -d '\n')
        echo "sanitized=$CLEANED" >> "$GITHUB_OUTPUT"

