name: 'Get Time in Timezone'
description: 'Get the current time in a specified timezone in ISO 8601 format'

inputs:
  timezone:
    description: 'The timezone to use (e.g., America/Argentina/Buenos_Aires)'
    required: true
    default: 'UTC'

outputs:
  current-time:
    description: 'Current time in the specified timezone (ISO 8601 format)'
    value: ${{ steps.time_step.outputs.current-time }}

runs:
  using: "composite"
  steps:
    - name: Get time in input timezone
      id: time_step
      shell: bash
      run: |
        echo "current-time=$(TZ='${{ inputs.timezone }}' date +%Y-%m-%dT%H:%M:%S%z)" >> "$GITHUB_OUTPUT"