name: Lint Dockerfile

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'debug'
        type: choice
        options:
          - info
          - warning
          - debug

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set default log level
        id: loglevel
        run: |
          echo "LOGLEVEL=${{ github.event.inputs.logLevel || 'info' }}" >> "$GITHUB_ENV"

      - name: Run Hadolint on Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
          config: .hadolint.yaml
          failure-threshold: error